### ISSUE TITLE
建议使用行政区划代码代替目前的直接使用城市名称

### ISSUE THREAD

**Issue by Initial-heart-1** [zydp/WeatherInfos#1]
如题。我认为这样有显而易见的好处：
- 无需对请求地址进行 URL Encode，简化调用流程，更方便调用。
- 不存在可能的编码问题导致请求异常，如分别使用 GBK 和 UTF-8 对 URL 进行编码。
- 泛用性、鲁棒性更强。区划代码可以有效的避免因取得的输入异常而导致的请求异常，且由官方发布，具有权威性，得到的支持更广。

当然，不知道 OW 是否还在维护该项目，如果没有，那么请务必告诉我，我会 Fork 它。

附：[2020年12月中华人民共和国县以上行政区划代码](https://www.mca.gov.cn/article/sj/xzqh/2020/20201201.html)

**Comment by zydp** [comment]
这两天忙，稍等一下。

**Comment by Initial-heart-1** [comment]
好的

**Comment by zydp** [comment]
你好，下午本想根据你提供的issue对程序进行完善。但在认真的观察行政区域代码后，我觉得当前程序所提供的，根据地理位置进行天气查询的方式更为妥善一些。主要说明如下：

行政区划分代码，其颗粒度仍不够细以及不够完善。 许多县、区、旗等地方，并没有在行政区域代码中得到体现
  - 如一些特别行政区香港、澳门等地区并无子区域进行划分
  - 如新林、加格达奇等类似地方在你提供的相关数据中并无法获得有效的行政区域代码
  - 类似雄安新区等新划分地区在所提供的数据中也未进行体现
  - 地理位置有其当地独特的称谓，且该称谓并非像行政区名那样官方与正式，如‘克孜勒苏柯尔克孜自治州‘在当地则被称为’克州‘
  
综上所述，可能我无法满足你的需求对程序进行修改。如果你有一些特殊的要求，可自行fork后进行一些定制修改。
另，如果你无法确定所在地天气查询的参数，可以调用以下接口获取详细的地址位置信息：
按照 省->市->县 进行数据的获取，北京、上海、天津等地区会比较特殊，如查询北京，需提供:"北京,北京"
- http://ip:port/citylist?city=北京,北京
- http://ip:port/citylist?city=黑龙江
- http://ip:port/citylist?city=黑龙江,大庆

**Comment by Initial-heart-1** [comment]
此处列出的是县级及以上的行政区划代码，但实际上，县级以下单位也有行政规划代码。《中华人民共和国乡镇行政区划简册》中有详细记载，粒度基本到街道级。虽然如此，使用这个表显然不太明智，因为实在是太多了——这玩意儿 648 页，而且一本 RMB 280（2021）。虽然 648 页里不是全都是区划代码，但区划代码占比很高。
当然，你提到的香港特别行政区、澳门特别行政区（及台湾省），这个没在网上找到相关官方资料，这个应该确实是缺陷。
你所述新林、加格达奇等，不属于上表应列出的范围内，因为它们是县级以下行政单位。雄安新区同理，这些都是有区划代码的。
对于地理位置的独特称谓，我认为这应该是需要特别注意的。通常，应以官方发布信息为准，以避免不同称呼造成的麻烦。这跟推广普通话是一个意思，意义在于方便沟通交流，在这里是方便调用 API。
当然，基于你列出的原因并综合上述信息，我认为使用民政部发布的区划代码确实不太合适。
但，还有一个更狠的，没有在 issue 里放出来是因为粒度真的细到离谱......
就是国家统计局发布的 [全国统计用区划代码和城乡划分代码](http://www.stats.gov.cn/sj/tjbz/tjyqhdmhcxhfdm/2022/index.html)。这份码表的粒度我想应该完全满足天气API的需求（街道-社区级），对于直辖市，其地域跨度大多数时候应该无需分区。当然，这份码表也不包含香港特别行政区、澳门特别行政区及台湾省，但可以使用邮编进行代替。因为与直辖市一样，除台湾省外，这些单位的地域跨度无需分区。台湾省的天气数据是唯一的难点，但作为一个特例处理也不是不行。
你可能会好奇为什么我如此执着的想要使用编码代替直接输入地名进行请求，因为我最近正尝试在较难对中文进行编码的 IoT 设备上实现天气查询。

**Comment by Initial-heart-1** [comment]
为保证向前兼容性，我的建议是保留现有的查询方法，另外新做一个接口用于编码查询。这样这个功能就可以作为 `enhancement` 而不是带有严重破坏性的 `update`。

**Comment by zydp** [comment]
好吧，这我得承认。IoT设备确实会在中文编码这块显得比较繁琐，迟一些我会增加一个通过’编码’查询的入口，’编码’不再会是汉字，但’编码’也不会是行政区域代码或是邮编。

**Comment by Initial-heart-1** [comment]
好的，感谢。

**Comment by zydp** [comment]
hi，下午看了下代码，稍做调整，增加了拼音的支持。
其实在代码内部每个最终地区是有相关代码(一串数字)的，但是因为仅数字无法涵盖所有地区，会导致数字无法在接口中通用，因此我新增了关于拼音的支持，使用方法示例在这 [示例](https://github.com/zydp/WeatherInfos#2023-03-19-更新)

> 容器境像已经更新 [容器部署](https://github.com/zydp/WeatherInfos#在容器中使用)
